
services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Aquí defines la contraseña para el usuario root
      MYSQL_DATABASE: masket      # Base de datos predeterminada
    ports:
      - "3306:3306" 
    volumes:
      - ./mysql_data:/var/lib/mysql  
      - ./back/laravel.sql:/docker-entrypoint-initdb.d/laravel.sql 

  # Adminer para gestionar la base de datos
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db  
    ports: 
      - 9092:8080

  # Servicio de la aplicación Vue.js
  vue-app:
    image: node:18
    working_dir: /app
    volumes:
      - ./front/basket:/app  
    ports:
      - "5173:5173"  
    command: /bin/bash -c "npm install && npm run dev" 
    depends_on:
      - db  

  # Servicio de la aplicación Laravel (back)
  laravel:
    image: php:8.2-fpm
    volumes:
      - ./back/laravel:/var/www/  # Asume que el código Laravel está en ./back/laravel
    working_dir: /var/www
    ports:
     - "8000:8000"  
    depends_on:
      - db
    command: bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev && docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install gd pdo pdo_mysql && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && composer install && php artisan key:generate && php artisan migrate && php artisan serve --host=0.0.0.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: masket
      DB_USERNAME: root
      DB_PASSWORD: root
