
services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masket
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "1000:3306"
    volumes:
      # Persistencia de datos
      - ./mysql_data:/var/lib/mysql
      # Archivo SQL para inicializar la base de datos
      - ./back/laravel.sql:/docker-entrypoint-initdb.d/laravel.sql
  

  # Adminer para gestionar la base de datos
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9092:8080"
   

  app:
    build:
      context: ./back/laravel
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000" 
    depends_on:
      - db
