services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masket
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./back/laravel.sql:/docker-entrypoint-initdb.d/laravel.sql

  # Adminer para gestionar la base de datos
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9092:8080

  # Servicio de la aplicación Vue.js
  vue-app:
    image: node:18
    working_dir: /app
    volumes:
      - ./front/basket:/app
    ports:
      - "5173:5173"
    command: /bin/bash -c "npm install && npm run dev"
    depends_on:
      - db

  # Servicio de la aplicación Laravel (back)
  laravel:
    build: ./back/laravel
    volumes:
      - ./back/laravel:/var/www/
    working_dir: /var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "composer install && php artisan key:generate && php artisan migrate && php artisan serve --host=0.0.0.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: masket
      DB_USERNAME: root
      DB_PASSWORD: root

  # Servicio Node.js
  node:
    image: node:18
    volumes:
      - ./back/node:/app  # Monta el directorio del servidor
    working_dir: /app
    ports:
      - "1234:1234"  # Exponer el puerto donde correrá el servidor
    command: /bin/bash -c "npm install && node server.js"  # Asegúrate de instalar dependencias antes de ejecutar
    depends_on:
      - db  # Si dependiera de la base de datos
      - laravel  # Si utiliza la API de Laravel
    environment:
      NODE_ENV: development  # Ambiente de desarrollo
