services:
  # Base de dades MySQL (masket)
  # anomeneu-la com vulgueu, però recordeu que ha de coincidir amb el nom
  # que poseu a la configuració de la connexió de l'aplicació (i el depends_on de l'adminer)
  # Crearà una carpeta "./mysql_data" on guardarà les dades de la base de dades
  # Si esborreu la carpeta, la BBDD estarà buida i podreu començar des de 0 
  # També crearà una BBBDD "botiga" pq. la imatge de mysql executa els fitxers
  # que hi hagi a la carpeta "docker-entrypoint-initdb.d" al primer inici
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masket
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    ports:
      - 3010:3306
    volumes:
      # Per guardar les dades de forma persistent
      # La carpeta de l'esquerra HA D'EXISTIR
      - ./mysql_data:/var/lib/mysql
      # Per crear algunes taules al primer inici
      - ./back/takeOutFit.sql:/docker-entrypoint-initdb.d/dades.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9090:8080"